# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
  include:
  - r: devel
    env: USE_BOXR_PASSWORD='false'
  - r: release
    env: USE_BOXR_PASSWORD='true'
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
    env: USE_BOXR_PASSWORD='false'

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

branches:
  only:
    - master
    
addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev
  